CREATE TABLE IF NOT EXISTS `rate`(
    `id` VARCHAR(64) NOT NULL,
    `date_time` DATETIME NOT NULL,
    `day` DATE NOT NULL,
    `bid` FLOAT(5,2) NOT NULL,
    `ask` FLOAT(5,2) NOT NULL,
    `open` FLOAT(5,2) NOT NULL,
    `high` FLOAT(5,2) NOT NULL,
    `low` FLOAT(5,2) NOT NULL,
    `prev_1_minutes_id` VARCHAR(64) NOT NULL,
    `prev_5_minutes_id` VARCHAR(64) NOT NULL,
    `next_1_minutes_id` VARCHAR(64) NOT NULL,
    `next_5_minutes_id` VARCHAR(64) NOT NULL,
    `rate_change_bid_1_minutes` FLOAT(10,6),
    `rate_change_bid_5_minutes` FLOAT(10,6),
    `fluctuation_bid_1_minutes` FLOAT(10,6),
    `fluctuation_bid_5_minutes` FLOAT(10,6),
    `rate_change_ask_1_minutes` FLOAT(10,6),
    `rate_change_ask_5_minutes` FLOAT(10,6),
    `fluctuation_ask_1_minutes` FLOAT(10,6),
    `fluctuation_ask_5_minutes` FLOAT(10,6),
    PRIMARY KEY(`id`),
    UNIQUE(`prev_1_minutes_id`),
    UNIQUE(`prev_5_minutes_id`),
    UNIQUE(`next_1_minutes_id`),
    UNIQUE(`next_5_minutes_id`),
    index (`rate_change_bid_1_minutes`),
    index (`rate_change_bid_5_minutes`),
    index (`fluctuation_bid_1_minutes`),
    index (`fluctuation_bid_5_minutes`),
    index (`rate_change_ask_1_minutes`),
    index (`rate_change_ask_5_minutes`),
    index (`fluctuation_ask_1_minutes`),
    index (`fluctuation_ask_5_minutes`),
    index (`day`, `bid`),
    index (`day`, `ask`),
    index (`date_time`)
);

CREATE TABLE IF NOT EXISTS `oanda_chart_queue`(
    `uuid` VARCHAR(64) NOT NULL,
    `date_time` DATETIME NOT NULL,
    `open` FLOAT(10,6) NOT NULL,
    `high` FLOAT(10,6) NOT NULL,
    `low` FLOAT(10,6) NOT NULL,
    `close` FLOAT(10,6) NOT NULL,
    `volume` FLOAT(10,6) NOT NULL,
    `volume_ma` FLOAT(10,6) NOT NULL,
    PRIMARY KEY(`uuid`),
    index (`date_time`)
);

CREATE TABLE IF NOT EXISTS `oanda_chart`(
    `id` VARCHAR(64) NOT NULL,
    `date_time` DATETIME NOT NULL,
    `day` DATE NOT NULL,
    `open` FLOAT(10,6) NOT NULL,
    `high` FLOAT(10,6) NOT NULL,
    `low` FLOAT(10,6) NOT NULL,
    `close` FLOAT(10,6) NOT NULL,
    `volume` FLOAT(10,6) NOT NULL,
    `volume_ma` FLOAT(10,6) NOT NULL,
    `prev_5_minutes_id` VARCHAR(64) NOT NULL,
    `next_5_minutes_id` VARCHAR(64) NOT NULL,
    `rate_change_open_5_minutes` FLOAT(10,6),
    `fluctuation_open_5_minutes` FLOAT(10,6),
    `rate_change_close_5_minutes` FLOAT(10,6),
    `fluctuation_close_5_minutes` FLOAT(10,6),
    `rate_change_high_5_minutes` FLOAT(10,6),
    `fluctuation_high_5_minutes` FLOAT(10,6),
    `rate_change_low_5_minutes` FLOAT(10,6),
    `fluctuation_low_5_minutes` FLOAT(10,6),
    PRIMARY KEY(`id`),
    UNIQUE(`prev_5_minutes_id`),
    UNIQUE(`next_5_minutes_id`),
    index (`rate_change_open_5_minutes`),
    index (`fluctuation_open_5_minutes`),
    index (`rate_change_close_5_minutes`),
    index (`fluctuation_close_5_minutes`),
    index (`rate_change_high_5_minutes`),
    index (`fluctuation_high_5_minutes`),
    index (`rate_change_low_5_minutes`),
    index (`fluctuation_low_5_minutes`),
    index (`day`, `high`),
    index (`day`, `low`),
    index (`date_time`)
);