server:
  port: "8080"

spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/re_mgr}"
    username: "${SPRING_DATASOURCE_USERNAME:app}"
    password: "${SPRING_DATASOURCE_PASSWORD:secret}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
  servlet:
    multipart:
      max-file-size: "20MB"
      max-request-size: "20MB"
  messages:
    basename: "messages/validationMessages"
    encoding: "UTF-8"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: "classpath*:/mybatis/sql/**/*.xml"

logging:
  level:
    root: INFO

re-mgr:
  users:
    - name: "admin"
      password: "admin"
      roles:
        - "ADMIN"
        - "USER"
    - name: "user"
      password: "user"
      roles:
        - "USER"